[kafka]
kafka-01 ansible_host=172.31.0.98
kafka-02 ansible_host=172.31.15.235
kafka-03 ansible_host=172.31.8.244

[kafka_ui]
kafka-ui-01 ansible_host=172.31.34.4
kafka-ui-02 ansible_host=172.31.19.172


[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/kafka-lab-key.pem