---
- name: Setup common on all nodes
  hosts: kafka
  become: yes
  roles:
    - common
    - java

- name: Install Kafka cluster
  hosts: kafka
  become: yes
  roles:
    - installation

- name: Verify Kafka cluster
  hosts: kafka
  become: yes
  roles:
    - verify

# - name: Deploy Kafka UI and Keycloak
#   hosts: kafka_ui
#   become: yes
#   roles:
#     - kafka_ui